# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
#Note: this may lack maturity
version: 2.1

commands:
  end-to-end-tests-config-check-command:
    steps:
      - checkout
      - run: #Configuration check
          echo "Starting the configuration check." 
          && cd src/test/java/jl/project/
          && grep "public static final boolean GRID_NOT_USED = true;" ./StringExternalization.java 
          && grep "//public static final String ANGULAR_SERVER_URL = \"http://192" ./StringExternalization.java 
          
executors:
  end-to-end-tests-executor:
    docker:
      # primary container
      # https://hub.docker.com/u/circleci/
      - image: circleci/openjdk

jobs:
  end-to-end-tests-config-check-job:
    executor: end-to-end-tests-executor
    steps:
      - end-to-end-tests-config-check-command      

workflows:  
  end-to-end-tests-config-check-workflow:
    jobs:
      - end-to-end-tests-config-check-job

